export const PRINTERS = [
  { model: 'mPOP', emulation: 'StarPRNT', printMode: 'append' },
  { model: 'FVP10', emulation: 'StarLine', printMode: 'append' },
  { model: 'TSP100', emulation: 'StarGraphic', printMode: 'appendBitmapText' },
  { model: 'TSP100IV', emulation: 'StarLine', printMode: 'append' },
  { model: 'TSP65011', emulation: 'StarLine', printMode: 'append' },
  { model: 'TSP7001', emulation: 'StarLine', printMode: 'append' },
  { model: 'TSP80011', emulation: 'StarLine', printMode: 'append' },
  { model: 'SP700', emulation: 'StarDotImpact', printMode: 'append' },
  { model: 'SM-S210i', emulation: 'EscPosMobile', printMode: 'append' },
  { model: 'SM-S220i', emulation: 'EscPosMobile', printMode: 'append' },
  { model: 'SM-S230i', emulation: 'EscosMobile', printMode: 'append' },
  { model: 'SM-T300i/T300', emulation: 'EscPosMobile', printMode: 'append' },
  { model: 'SM-T400i', emulation: 'EscosMobile', printMode: 'append' },
  { model: 'SM-L200', emulation: 'StarPRNT', printMode: 'append' },
  { model: 'SM-L300', emulation: 'StarPRNT', printMode: 'append' },
  { model: 'BSC10', emulation: 'EscPos', bt: 'BT:BSC10', printMode: 'append' },
  { model: 'SM-S210i StarPRNT', emulation: 'StarPRNT', printMode: 'append' },
  { model: 'SM-S220i StarPRNT', emulation: 'StarPRNT', printMode: 'append' },
  { model: 'SM-S230i StarPRNT', emulation: 'StarPRNT', printMode: 'append' },
  { model: 'SM-T300i/T300 StarPRNT', emulation: 'StarPRNT', printMode: 'append' },
  { model: 'SM-T400i StarPRNT', emulation: 'StarPRNT', printMode: 'append' },
]
