export declare const Card: any;
export declare const BusinessHero: any;
export declare const BusinessContent: any;
export declare const BusinessInfo: any;
export declare const BusinessCategory: any;
export declare const Metadata: any;
export declare const BusinessState: any;
export declare const BusinessLogo: any;
export declare const Reviews: any;
