export declare const AccordionSection: any;
export declare const Accordion: (props: any) => JSX.Element;
export declare const ProductInfo: any;
export declare const ProductQuantity: any;
export declare const ContentInfo: any;
export declare const ProductImage: any;
export declare const AccordionContent: any;
export declare const ProductOptionsList: any;
export declare const ProductOption: any;
export declare const ProductSubOption: any;
export declare const ProductComment: any;
